# Generated by Django 3.1.3 on 2020-12-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ffem',
            new_name='dffem',
        ),
    ]
