# Generated by Django 3.1.3 on 2020-12-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_dfegcn_dfegdp_dffcp_dffec_dffeme_dffemh_dfscs_dfseg_dfsem_dfsep_dfsvbt_dfsvcc_dfsvds_dfsvse_dsfda_ds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dffeme',
        ),
    ]
