# Generated by Django 3.1.6 on 2021-02-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_auto_20201207_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dfegcn',
        ),
        migrations.DeleteModel(
            name='dfegdp',
        ),
        migrations.DeleteModel(
            name='dffcp',
        ),
        migrations.DeleteModel(
            name='dffec',
        ),
        migrations.DeleteModel(
            name='dffem',
        ),
        migrations.DeleteModel(
            name='dffemh',
        ),
        migrations.DeleteModel(
            name='dfscs',
        ),
        migrations.DeleteModel(
            name='dfseg',
        ),
        migrations.DeleteModel(
            name='dfsem',
        ),
        migrations.DeleteModel(
            name='dfsep',
        ),
        migrations.DeleteModel(
            name='dfsvbt',
        ),
        migrations.DeleteModel(
            name='dfsvcc',
        ),
        migrations.DeleteModel(
            name='dfsvds',
        ),
        migrations.DeleteModel(
            name='dfsvse',
        ),
        migrations.DeleteModel(
            name='dsfda',
        ),
        migrations.DeleteModel(
            name='dsfos',
        ),
        migrations.DeleteModel(
            name='dsfpd',
        ),
        migrations.DeleteModel(
            name='dsfps',
        ),
        migrations.DeleteModel(
            name='dstca',
        ),
        migrations.DeleteModel(
            name='dstdm',
        ),
        migrations.DeleteModel(
            name='dstds',
        ),
        migrations.DeleteModel(
            name='dstem',
        ),
        migrations.DeleteModel(
            name='dtfcl',
        ),
        migrations.DeleteModel(
            name='dtfds',
        ),
        migrations.DeleteModel(
            name='dtfml',
        ),
        migrations.DeleteModel(
            name='dtftc',
        ),
        migrations.DeleteModel(
            name='dtsai',
        ),
        migrations.DeleteModel(
            name='dtscd',
        ),
        migrations.DeleteModel(
            name='dtscn',
        ),
        migrations.DeleteModel(
            name='dtsiot',
        ),
    ]
