# Generated by Django 3.1.6 on 2021-02-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0008_auto_20210216_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
