# Generated by Django 3.1.6 on 2021-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub', '0011_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=900)),
                ('option1', models.CharField(max_length=800)),
                ('option2', models.CharField(max_length=800)),
                ('option3', models.CharField(max_length=800)),
                ('option4', models.CharField(max_length=800)),
                ('answer', models.CharField(max_length=800)),
                ('category', models.CharField(max_length=400)),
            ],
        ),
    ]
