# Generated by Django 3.1.6 on 2021-02-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0012_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
