# Generated by Django 3.1.3 on 2020-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
            ],
        ),
    ]
