# Generated by Django 3.1.3 on 2020-11-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_extenduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='department',
            new_name='dept',
        ),
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
