# Generated by Django 3.1.3 on 2020-11-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20201129_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='extenduser',
            old_name='dept',
            new_name='department',
        ),
    ]
