# Generated by Django 3.1.3 on 2020-11-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20201129_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
