# Generated by Django 3.1.3 on 2020-11-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_delete_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='department',
        ),
    ]
