# Generated by Django 3.1.3 on 2020-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_remove_extenduser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=100)),
                ('sub_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
            ],
        ),
    ]
