# Generated by Django 3.1.3 on 2020-11-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
    ]
