# Generated by Django 3.1.3 on 2020-12-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.DeleteModel(
            name='question',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
