# Generated by Django 3.1.3 on 2020-12-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20201204_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extendUser',
        ),
    ]
